-- ═══════════════════════════════════════════════════════════════════════
--  ksqlDB Init Script  –  E-Commerce Order Analytics
--  Executed automatically by docker/ksql-init.sh on docker compose up
--  Can also be run manually:
--    docker exec -it ksqldb-cli ksql http://ksqldb-server:8088
--    then: RUN SCRIPT '/ksql/init.sql';
--
--  Field names match Jackson camelCase serialisation from the Java models.
-- ═══════════════════════════════════════════════════════════════════════

SET 'auto.offset.reset' = 'earliest';

-- ─────────────────────────────────────────────────────────────────────
--  STREAMS  (unbounded, append-only event logs backed by Kafka topics)
-- ─────────────────────────────────────────────────────────────────────

-- 1. Raw orders arriving from the Spring Boot app
CREATE STREAM IF NOT EXISTS orders_stream (
    orderId    VARCHAR,
    customerId VARCHAR,
    productId  VARCHAR,
    category   VARCHAR,
    amount     DOUBLE,
    quantity   INT,
    status     VARCHAR,
    timestamp  BIGINT
) WITH (
    KAFKA_TOPIC  = 'orders',
    VALUE_FORMAT = 'JSON',
    TIMESTAMP    = 'timestamp'
);

-- 2. Orders enriched with product name/brand (written by Kafka Streams topology)
CREATE STREAM IF NOT EXISTS enriched_orders_stream (
    orderId     VARCHAR,
    customerId  VARCHAR,
    productId   VARCHAR,
    productName VARCHAR,
    brand       VARCHAR,
    category    VARCHAR,
    amount      DOUBLE,
    quantity    INT,
    status      VARCHAR,
    timestamp   BIGINT
) WITH (
    KAFKA_TOPIC  = 'enriched-orders',
    VALUE_FORMAT = 'JSON',
    TIMESTAMP    = 'timestamp'
);

-- 3. Fraud alerts generated by Kafka Streams topology (amount > $500)
CREATE STREAM IF NOT EXISTS fraud_alerts_stream (
    alertId     VARCHAR,
    orderId     VARCHAR,
    customerId  VARCHAR,
    productId   VARCHAR,
    productName VARCHAR,
    category    VARCHAR,
    amount      DOUBLE,
    alertType   VARCHAR,
    severity    VARCHAR,
    timestamp   BIGINT
) WITH (
    KAFKA_TOPIC  = 'fraud-alerts',
    VALUE_FORMAT = 'JSON'
);

-- ─────────────────────────────────────────────────────────────────────
--  PERSISTENT QUERIES  (run continuously, write back to Kafka topics)
--  These are ksqlDB's equivalent of Kafka Streams' stateful processors
-- ─────────────────────────────────────────────────────────────────────

-- 4. High-value orders – streaming filter (ksqlDB side fraud screen)
--    Demonstrates: STREAM → STREAM transformation via WHERE clause
CREATE STREAM IF NOT EXISTS high_value_orders AS
    SELECT orderId, customerId, productId, category, amount, quantity, timestamp,
           'HIGH_VALUE' AS flag
    FROM   orders_stream
    WHERE  amount > 500
    EMIT CHANGES;

-- 5. Electronics-only order stream – category routing
--    Demonstrates: topic fan-out pattern using ksqlDB STREAM filter
CREATE STREAM IF NOT EXISTS electronics_orders AS
    SELECT *
    FROM   orders_stream
    WHERE  category = 'Electronics'
    EMIT CHANGES;

-- 6. Per-category sales – 1-minute TUMBLING window
--    Demonstrates: windowed GROUP BY aggregation (COUNT, SUM, AVG, MAX)
--    Window type: TUMBLING – non-overlapping fixed-size buckets
CREATE TABLE IF NOT EXISTS category_sales_1min AS
    SELECT
        category,
        COUNT(*)      AS order_count,
        SUM(amount)   AS total_sales,
        AVG(amount)   AS avg_order_value,
        MAX(amount)   AS max_order_value,
        SUM(quantity) AS total_items
    FROM   orders_stream
    WINDOW TUMBLING (SIZE 1 MINUTE)
    GROUP BY category
    EMIT CHANGES;

-- 7. Per-category sales – 1-hour HOPPING window (updates every 15 min)
--    Demonstrates: HOPPING window – overlapping, each event appears in N windows
CREATE TABLE IF NOT EXISTS category_sales_hourly AS
    SELECT
        category,
        COUNT(*)    AS order_count,
        SUM(amount) AS total_sales,
        AVG(amount) AS avg_value
    FROM   orders_stream
    WINDOW HOPPING (SIZE 1 HOUR, ADVANCE BY 15 MINUTES)
    GROUP BY category
    EMIT CHANGES;

-- 8. Running customer spend totals – no window (all-time aggregate)
--    Demonstrates: unbounded aggregation / materialised TABLE
CREATE TABLE IF NOT EXISTS customer_spending AS
    SELECT
        customerId,
        COUNT(*)    AS total_orders,
        SUM(amount) AS total_spent,
        MAX(amount) AS largest_order,
        AVG(amount) AS avg_order_value
    FROM   orders_stream
    GROUP BY customerId
    EMIT CHANGES;

-- 9. Fraud summary by category (from the fraud-alerts topic)
--    Demonstrates: aggregating over a filtered downstream stream
CREATE TABLE IF NOT EXISTS fraud_by_category AS
    SELECT
        category,
        COUNT(*)    AS alert_count,
        SUM(amount) AS flagged_amount,
        MAX(amount) AS max_flagged
    FROM   fraud_alerts_stream
    GROUP BY category
    EMIT CHANGES;
